apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
  labels:
    app: dev
spec:
  selector:
    matchLabels:
      app: dev
  replicas: 1
  template:
    metadata:
      labels:
        app: dev
    spec: 
      containers:
        - name: mongo-container
          image: mongo
          ports:
            - containerPort: 2017
          env:
          -  name: MONGO_INITDB_ROOT_USERNAME
             valueFrom:
               secretKeyRef:
                 name: mongo-secret
                 key: username
          -  name: MONGO_INITDB_ROOT_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: mongo-secret
                 key: password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deploy
  labels:
    app: dev
spec:
  selector:
    matchLabels:
      app: dev
  replicas: 1
  template:
    metadata:
      labels:
        app: dev
    spec: 
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
          -  name: ME_CONFIG_MONGODB_ADMINUSERNAME
             valueFrom:
               secretKeyRef:
                 name: mongo-secret
                 key: username
          -  name: ME_CONFIG_MONGODB_ADMINPASSWORD
             valueFrom:
               secretKeyRef:
                 name: mongo-secret
                 key: password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: service