apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-web
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: nginx-pod
      labels:
        app: web
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
--- 
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
spec:
  selector:
    app: web
  type: NodePort
  ports:
  -  targetPort: 80
     port: 80
     nodePort: 32000
     protocol: TCP