apiVersion: v1
kind: Service
metadata: 
  name: mongo-internal
  
spec:
  selector:
    app: dev
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata: 
  name: mongo-external

spec:
  selector:
    app: dev
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP