apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto
data: 
  mosquitto.conf: | 
    log_dest stdout
    log_type all
    log_timestamp true
    listener 9001
    #Name of author is Tolulope
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-mosquitto
type: Opaque
data:
  secret.file: |
    TXkgbGlmZSBpcyBiZWF1dGlmdWw=


---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mosquitto
  labels:
    app: mosq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosq
  template:
    metadata:
      labels:
        app: mosq
    spec:
      containers:
        - name: mosquito
          image: eclipse-mosquitto:1.6
          ports:
            - containerPort: 1883
          volumeMounts:
            - mountPath: /mosquitto/config
              name: mosquitto
            - mountPath: /secret
              name: secret-mosquitto
      volumes:
        - name: mosquitto
          configMap:
            name: mosquitto
        - name: secret-mosquitto
          secret:
            secretName: secret-mosquitto
      

